# ref - https://github.com/JohnnyMorganz/StyLua#options
line_endings = "Unix"
indent_type = "Spaces"
indent_width = 2
quote_style = "AutoPreferDouble"
call_parantheses = "None"
collapse_simple_statement = "Always"
